version: '3'

services:
  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=db_password
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
      - MYSQL_DATABASE=db_name
      - TZ=Europe/Moscow
      - LANG=C.UTF-8
    cap_add:
      - SYS_NICE
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PHP_IDE_CONFIG=serverName=template.loc
    depends_on:
      - db
    extra_hosts:
      - host.docker.internal:host-gateway

  httpd:
    build:
      context: ./docker/apache
      dockerfile: Dockerfile
    ports:
      - "8888:80"
    volumes:
      - .:/app
    depends_on:
      - php
