controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

root:
    path: /
    controller: App\Controller\AppController::rootAction

parse:
    path: /parse
    controller: App\Controller\AppController::parseAction

article:
    path: /article/{id}
    controller: App\Controller\AppController::articleAction